### ISSUE TITLE
solution for bounty 2 and bounty 3 using ibc v3's interchain account

### ISSUE THREAD

**Issue by catShaark** [CosmosContracts/bounties#12] opened 2022-01-27 04:12 UTC
what I did:
- osmosis : upgrade ibc to v3, unimport bech32-ibc from osmosis since it doesn't work with ibc v3
- wamd : upgrade ibc to v3, make change to contract ibc handler so that they support v3's interchain account
- make a smart contract that support swaping and pooling via interchain account, allows user to do so using only one contract transaction
This has one downside which is that users have to specify exactly the amount of token out after swaping or pooling. User will receive that amount of token on their chosen account on osmosis. This amount can be easily calculated and put in an UI 

Once osmosis upgrade their ibc to v3 and wasmd supports interchain account, this contract will be usable

**Comment by romelukaku** [comment] 2022-01-27 04:12
here's is the contract's code: https://github.com/romelukaku/cw3/tree/gamm-contract

**Comment by romelukaku** [comment] 2022-01-27 04:38
this is my wasmd mod: https://github.com/notional-labs/wasmd.git
It needs some clean up, I'll do that soon

**Comment by JakeHartnell** [comment] 2022-01-30 22:37
Good start! A large part of the criteria was that the solution would work on mainnet, that's why the bounty status for the Osmosis bounties is currently `blocked`. However, if @dimiandre agrees, I think we could do a partial payment for this. That said, I have some feedback... 

Please make a separate repo for this contract: https://github.com/notional-labs/cw-plus/tree/gamm-contract

It's very messy the way you've done it (inside of a fork of `cw-plus`). Break it out into it's own `gamm-contract` repo and be sure to add a decent `README`.

**Comment by romelukaku** [comment] 2022-01-31 04:01
Yes, I will clean up my messy repo

**Comment by JakeHartnell** [comment] 2022-03-23 19:55
Closing as duplicate of #17

**Closed by JakeHartnell** 2022-03-23 19:55 UTC
